name: interaction
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.8.*
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch=1.12.1
  - numpy
  - scipy
  - matplotlib
  - pandas=1.4.4
  - ipdb
  - ipython
  - joblib
  - psutil
  - mpi4py
  - seaborn
  - click
  - tqdm
